/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** JavaScript представление NodeRecord */
export interface JsNodeRecord {
  /** ID ноды (BigInt в JS) */
  id: bigint
  /** Тип ноды */
  kind: number
  /** ID файла */
  fileId: number
  /** Offset имени в string table */
  nameOffset: number
  /** Версия ("main" или "__local") */
  version: string
  /** Экспортируется ли */
  exported: boolean
  /** ID заменяемой ноды (для инкрементального анализа) */
  replaces?: bigint
}
/** JavaScript представление EdgeRecord */
export interface JsEdgeRecord {
  /** ID источника */
  src: bigint
  /** ID назначения */
  dst: bigint
  /** Тип ребра */
  etype: number
  /** Версия */
  version: string
}
/** JavaScript представление AttrQuery */
export interface JsAttrQuery {
  version?: string
  kind?: number
  fileId?: number
  exported?: boolean
  name?: string
}
/** Вычислить детерминированный ID ноды на основе её характеристик */
export declare function computeNodeIdJs(nodeType: number, name: string, scope: string, path: string): bigint
/** GraphEngine - главный класс для работы с графом */
export declare class GraphEngine {
  /** Создать новый граф по указанному пути */
  constructor(path: string)
  /** Открыть существующий граф */
  static open(path: string): GraphEngine
  /** Добавить ноды в граф */
  addNodes(nodes: Array<JsNodeRecord>): void
  /** Добавить рёбра в граф */
  addEdges(edges: Array<JsEdgeRecord>): void
  /** Удалить ноду */
  deleteNode(id: bigint): void
  /** Удалить ребро */
  deleteEdge(src: bigint, dst: bigint, etype: number): void
  /** Получить ноду по ID */
  getNode(id: bigint): JsNodeRecord | null
  /** Проверить существование ноды */
  nodeExists(id: bigint): boolean
  /** Найти ноды по атрибутам */
  findByAttr(query: JsAttrQuery): Array<bigint>
  /** Найти ноды по типу */
  findByType(nodeType: number): Array<bigint>
  /** Получить соседей ноды */
  neighbors(id: bigint, edgeTypes: Array<number>): Array<bigint>
  /** Поиск в ширину (BFS) */
  bfs(startIds: Array<bigint>, maxDepth: number, edgeTypes: Array<number>): Array<bigint>
  /**
   * Поиск в глубину (DFS)
   * TODO: Implement DFS in GraphEngine
   */
  dfs(startIds: Array<bigint>, maxDepth: number, edgeTypes: Array<number>): Array<bigint>
  /** Flush данных на диск */
  flush(): void
  /** Компактификация данных */
  compact(): void
  /** Количество нод */
  nodeCount(): number
  /** Количество рёбер */
  edgeCount(): number
  /** Проверить является ли нода endpoint'ом */
  isEndpoint(id: bigint): boolean
  /**
   * Обновить версию ноды
   * TODO: Implement update_node_version in GraphEngine
   */
  updateNodeVersion(id: bigint, version: string): void
}
